export const specialists = [
    {
        name: "Анна Иванова",
        direction: "Психолог",
        specialization: "тревожность, депрессия, семейные конфликты",
        city: "Москва",
        experience: "7 лет",
        description: "стресс, мотивация, личностный рост",
        img: "/images/spec2.png",
        work_format: ["online","offline"],
        telegram_id:"8076698584",
    },
    {
        name: "Али Курбанов",
        direction: "Психотерапевт",
        specialization: "тревожность, депрессия, семейные конфликты",
        city: "Ташкент",
        experience: "10 лет",
        description: "тревожность, депрессия, семейные конфликты",
        img: "/images/spec1.png",
        work_format: ["online"],
        telegram_id:"8076698584",
    },
    {
        name: "Иван Петров",
        direction: "Клинический психолог",
        specialization: "тревожность, депрессия, семейные конфликты",
        city: "Санкт-Петербург",
        experience: "12 лет",
        description: "кризисные состояния, психосоматика",
        img: "/images/spec3.png",
        work_format: ["online"],
        telegram_id:"8076698584",
    },
    {
        name: "Иван Петров",
        direction: "Клинический психолог",
        specialization: "тревожность, депрессия, семейные конфликты",
        city: "Санкт-Петербург",
        experience: "12 лет",
        description: "кризисные состояния, психосоматика",
        img: "/images/spec4.png",
        work_format: ["online"],
        telegram_id:"8076698584",
    },
    {
        name: "Иван Петров",
        direction: "Клинический психолог",
        specialization: "тревожность, депрессия, семейные конфликты",
        city: "Санкт-Петербург",
        experience: "12 лет",
        description: "кризисные состояния, психосоматика",
        img: "/images/spec5.png",
        work_format: ["online"],
        telegram_id:"8076698584",
    },
    {
        name: "Иван Петров",
        direction: "Клинический психолог",
        specialization: "тревожность, депрессия, семейные конфликты",
        city: "Санкт-Петербург",
        experience: "12 лет",
        description: "кризисные состояния, психосоматика",
        img: "/images/spec6.png",
        work_format: ["online"],
        telegram_id:"8076698584",
    },
];
